#include <linux/miscdevice.h>
#include <linux/delay.h>
#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/init.h>
#include <linux/mm.h>
#include <linux/fs.h>
#include <linux/types.h>
#include <linux/delay.h>
#include <linux/slab.h>
#include <linux/errno.h>
#include <linux/ioctl.h>
#include <linux/cdev.h>
#include <linux/string.h>
#include <linux/list.h>
#include <asm/uaccess.h>
#include <asm/atomic.h>
#include <asm/unistd.h>
#include <linux/device.h>
#include <linux/input.h>
#include <linux/poll.h>
#include <linux/moduleparam.h>
#include <linux/platform_device.h>
#include <linux/earlysuspend.h>

#include "../../include/ShareMemoryStruct.h"

#include "../include/fly_soc.h"
#include "../include/driver_def.h"

#include "FlyCommon.h"
#include "FlyIO.h"
#include "FlySound.h"
#include "FlyKeyADC.h"
#include "FlyKeyExti.h"
#include "FlyKeyExec.h"
#include "FlyHALService.h"
#include "FlyHALSystem.h"
#include "FlyHALAudio.h"
#include "FlyHALVideo.h"
#include "FlyHALRadio.h"
#include "FlyHALDVD.h"
#include "FlyHALBT.h"
#include "FlyHALKey.h"
#include "FlyHALProc.h"
#include "FlyMCUProc.h"
#include "FlyIPCDriver.h"
#include "FlyHardCenter.h"
#include "FlyHALExdisplay.h"