obj-m += FlyHardwareDevice.o
obj-m += FlyHardware.o

FlyHardware-objs := FlyHardCenter.o FlyCommon.o FlyIO.o \
					FlyIPCDriver.o FlyMCUProc.o FlySound.o \
					FlyKeyADC.o FlyKeyExti.o FlyKeyExec.o FlyHALProc.o \
					FlyHALService.o FlyHALSystem.o FlyHALAudio.o FlyHALVideo.o \
					FlyHALRadio.o FlyHALDVD.o FlyHALBT.o FlyHALKey.o FlyHALExdisplay.o
